"""init schema

Revision ID: 850667bcae51
Revises: 
Create Date: 2026-05-28 14:47:49.935045

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '850667bcae51'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('apelido', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pendente', nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('senha_temporaria', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_apelido'), 'usuarios', ['apelido'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_status'), 'usuarios', ['status'], unique=False)
    op.create_table('desempate_palpite_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('contexto', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('ordem_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'contexto', 'grupo_id', name='uq_desempate_user_ctx_grupo')
    )
    op.create_index(op.f('ix_desempate_palpite_usuario_usuario_id'), 'desempate_palpite_usuario', ['usuario_id'], unique=False)
    op.create_table('logs_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('entidade', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('detalhes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_admin_acao'), 'logs_admin', ['acao'], unique=False)
    op.create_index(op.f('ix_logs_admin_admin_id'), 'logs_admin', ['admin_id'], unique=False)
    op.create_index(op.f('ix_logs_admin_created_at'), 'logs_admin', ['created_at'], unique=False)
    op.create_table('selecoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_fifa', sa.String(length=3), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('nome_pt', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('confederacao', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('bandeira_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_selecoes_codigo_fifa'), 'selecoes', ['codigo_fifa'], unique=True)
    op.create_index(op.f('ix_selecoes_grupo_id'), 'selecoes', ['grupo_id'], unique=False)
    op.create_table('aposta_classificacao_final',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('campeao_id', sa.Integer(), nullable=True),
    sa.Column('vice_id', sa.Integer(), nullable=True),
    sa.Column('terceiro_id', sa.Integer(), nullable=True),
    sa.Column('quarto_id', sa.Integer(), nullable=True),
    sa.Column('pontos_campeao', sa.Integer(), nullable=False),
    sa.Column('pontos_vice', sa.Integer(), nullable=False),
    sa.Column('pontos_terceiro', sa.Integer(), nullable=False),
    sa.Column('pontos_quarto', sa.Integer(), nullable=False),
    sa.Column('pontos_total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campeao_id'], ['selecoes.id'], ),
    sa.ForeignKeyConstraint(['quarto_id'], ['selecoes.id'], ),
    sa.ForeignKeyConstraint(['terceiro_id'], ['selecoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['vice_id'], ['selecoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('desempate_manual_grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=False),
    sa.Column('selecao_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('posicao BETWEEN 1 AND 4', name='ck_desempate_grupo_pos'),
    sa.ForeignKeyConstraint(['admin_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['selecao_id'], ['selecoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grupo_id', 'posicao', name='uq_desempate_grupo_pos')
    )
    op.create_index(op.f('ix_desempate_manual_grupo_grupo_id'), 'desempate_manual_grupo', ['grupo_id'], unique=False)
    op.create_table('desempate_manual_terceiros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=False),
    sa.Column('selecao_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('posicao BETWEEN 1 AND 12', name='ck_desempate_3os_pos'),
    sa.ForeignKeyConstraint(['admin_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['selecao_id'], ['selecoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('posicao')
    )
    op.create_table('partidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('fase', sa.String(length=20), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('mandante_id', sa.Integer(), nullable=True),
    sa.Column('visitante_id', sa.Integer(), nullable=True),
    sa.Column('slot_mandante', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('slot_visitante', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('origem_mandante_id', sa.Integer(), nullable=True),
    sa.Column('origem_mandante_tipo', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('origem_visitante_id', sa.Integer(), nullable=True),
    sa.Column('origem_visitante_tipo', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='nao_iniciado', nullable=False),
    sa.Column('placar_mandante', sa.Integer(), nullable=True),
    sa.Column('placar_visitante', sa.Integer(), nullable=True),
    sa.Column('classificado_id', sa.Integer(), nullable=True),
    sa.Column('fp_amarelos_mandante', sa.Integer(), server_default='0', nullable=True),
    sa.Column('fp_verm_2amarelo_mandante', sa.Integer(), server_default='0', nullable=True),
    sa.Column('fp_verm_direto_mandante', sa.Integer(), server_default='0', nullable=True),
    sa.Column('fp_amarelo_verm_mandante', sa.Integer(), server_default='0', nullable=True),
    sa.Column('fp_amarelos_visitante', sa.Integer(), server_default='0', nullable=True),
    sa.Column('fp_verm_2amarelo_visitante', sa.Integer(), server_default='0', nullable=True),
    sa.Column('fp_verm_direto_visitante', sa.Integer(), server_default='0', nullable=True),
    sa.Column('fp_amarelo_verm_visitante', sa.Integer(), server_default='0', nullable=True),
    sa.Column('estadio', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('cidade', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('placar_mandante IS NULL OR (placar_mandante >= 0 AND placar_mandante <= 30)', name='ck_partida_placar_mand'),
    sa.CheckConstraint('placar_visitante IS NULL OR (placar_visitante >= 0 AND placar_visitante <= 30)', name='ck_partida_placar_vis'),
    sa.ForeignKeyConstraint(['classificado_id'], ['selecoes.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['mandante_id'], ['selecoes.id'], ),
    sa.ForeignKeyConstraint(['origem_mandante_id'], ['partidas.id'], ),
    sa.ForeignKeyConstraint(['origem_visitante_id'], ['partidas.id'], ),
    sa.ForeignKeyConstraint(['visitante_id'], ['selecoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partidas_codigo'), 'partidas', ['codigo'], unique=True)
    op.create_index(op.f('ix_partidas_data_hora'), 'partidas', ['data_hora'], unique=False)
    op.create_index(op.f('ix_partidas_fase'), 'partidas', ['fase'], unique=False)
    op.create_index(op.f('ix_partidas_grupo_id'), 'partidas', ['grupo_id'], unique=False)
    op.create_index(op.f('ix_partidas_mandante_id'), 'partidas', ['mandante_id'], unique=False)
    op.create_index(op.f('ix_partidas_status'), 'partidas', ['status'], unique=False)
    op.create_index(op.f('ix_partidas_visitante_id'), 'partidas', ['visitante_id'], unique=False)
    op.create_table('palpites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('gols_mandante', sa.Integer(), nullable=False),
    sa.Column('gols_visitante', sa.Integer(), nullable=False),
    sa.Column('classificado_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('gols_mandante >= 0 AND gols_mandante <= 30', name='ck_palpite_gols_mand'),
    sa.CheckConstraint('gols_visitante >= 0 AND gols_visitante <= 30', name='ck_palpite_gols_vis'),
    sa.ForeignKeyConstraint(['classificado_id'], ['selecoes.id'], ),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'partida_id', name='uq_palpite_usuario_partida')
    )
    op.create_index(op.f('ix_palpites_partida_id'), 'palpites', ['partida_id'], unique=False)
    op.create_index(op.f('ix_palpites_usuario_id'), 'palpites', ['usuario_id'], unique=False)
    op.create_table('pontuacao_partidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('partida_id', sa.Integer(), nullable=False),
    sa.Column('pontos_gols_mandante', sa.Integer(), nullable=False),
    sa.Column('pontos_gols_visitante', sa.Integer(), nullable=False),
    sa.Column('pontos_resultado', sa.Integer(), nullable=False),
    sa.Column('pontos_placar_exato', sa.Integer(), nullable=False),
    sa.Column('pontos_classificado', sa.Integer(), nullable=False),
    sa.Column('pontos_total', sa.Integer(), nullable=False),
    sa.Column('calculado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['partida_id'], ['partidas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'partida_id', name='uq_pont_user_partida')
    )
    op.create_index(op.f('ix_pontuacao_partidas_partida_id'), 'pontuacao_partidas', ['partida_id'], unique=False)
    op.create_index(op.f('ix_pontuacao_partidas_pontos_total'), 'pontuacao_partidas', ['pontos_total'], unique=False)
    op.create_index(op.f('ix_pontuacao_partidas_usuario_id'), 'pontuacao_partidas', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pontuacao_partidas_usuario_id'), table_name='pontuacao_partidas')
    op.drop_index(op.f('ix_pontuacao_partidas_pontos_total'), table_name='pontuacao_partidas')
    op.drop_index(op.f('ix_pontuacao_partidas_partida_id'), table_name='pontuacao_partidas')
    op.drop_table('pontuacao_partidas')
    op.drop_index(op.f('ix_palpites_usuario_id'), table_name='palpites')
    op.drop_index(op.f('ix_palpites_partida_id'), table_name='palpites')
    op.drop_table('palpites')
    op.drop_index(op.f('ix_partidas_visitante_id'), table_name='partidas')
    op.drop_index(op.f('ix_partidas_status'), table_name='partidas')
    op.drop_index(op.f('ix_partidas_mandante_id'), table_name='partidas')
    op.drop_index(op.f('ix_partidas_grupo_id'), table_name='partidas')
    op.drop_index(op.f('ix_partidas_fase'), table_name='partidas')
    op.drop_index(op.f('ix_partidas_data_hora'), table_name='partidas')
    op.drop_index(op.f('ix_partidas_codigo'), table_name='partidas')
    op.drop_table('partidas')
    op.drop_table('desempate_manual_terceiros')
    op.drop_index(op.f('ix_desempate_manual_grupo_grupo_id'), table_name='desempate_manual_grupo')
    op.drop_table('desempate_manual_grupo')
    op.drop_table('aposta_classificacao_final')
    op.drop_index(op.f('ix_selecoes_grupo_id'), table_name='selecoes')
    op.drop_index(op.f('ix_selecoes_codigo_fifa'), table_name='selecoes')
    op.drop_table('selecoes')
    op.drop_index(op.f('ix_logs_admin_created_at'), table_name='logs_admin')
    op.drop_index(op.f('ix_logs_admin_admin_id'), table_name='logs_admin')
    op.drop_index(op.f('ix_logs_admin_acao'), table_name='logs_admin')
    op.drop_table('logs_admin')
    op.drop_index(op.f('ix_desempate_palpite_usuario_usuario_id'), table_name='desempate_palpite_usuario')
    op.drop_table('desempate_palpite_usuario')
    op.drop_index(op.f('ix_usuarios_status'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_apelido'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('grupos')
    # ### end Alembic commands ###
